version: '3.9'
services:
  app:
    container_name: app
    working_dir: /app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://user:password@database:5432/shopify_like
    restart: always
    command: npm run dev
    volumes:
      - .:/app
    networks:
      - backend

  database:
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=shopify_like
    command: ["postgres", "-c", "listen_addresses=*"]
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shopify_like"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  database: {}
